### ISSUE TITLE
Display metadata in currently selected CKAN language

### ISSUE THREAD

**Issue by metaodi** [open-data/ckanext-fluent#12]
For the Swiss portal, we want to use ckanext-fluent to manage the multilingual metadata. The currently available display snippets contain a `for` to display the metadata in all available languages. We would want to only display one language, which is the one that the user is currently using.

Would you be interested in receiving PR(s), which implement this feature or should we rather create a new extension based on this one?

Related would be to extend the multilingual functionality to all fields, as there are currently some fields that are not supported by this extensions (like the `title`).

What do you think?

**Comment by wardi** [comment]
Yes, just displaying the users' language would be better.  Might be nice to indicate somehow when we're showing them a language that isn't theirs (because theirs isn't available)

Fluent does work for title and notes (and name in resources) but you have to either make template changes or add a IPackageController plugin with before_view that replaces those fields with the users preferred language.

**Comment by TkTech** [comment]
@wardi [fr | en | sp | br ] .... etc... shown under the text, clicking one uses a small javascript widget to switch that particular field?

**Comment by wardi** [comment]
@TkTech we can already switch languages for the whole page with the CKAN language selector. I just meant an indication when we're displaying a language that is not the one the user requested. Like

[en] Fishery Data

when the user has selected, say German, but the only languages available are English and French and we decided to show the English version instead of nothing.

**Comment by TkTech** [comment]
@wardi That's what I meant as well. the selector would only display to allow to select among alternative languages.

**Comment by wardi** [comment]
@TkTech good question. Switching the page language is another way to see the alternate versions, but that changes all the labels too, which could be confusing.

Having a language selector on every field might be more confusing, and would be annoying to have to click a whole bunch of fields to change all the languages

How about that [en] indicator popping up a menu like you suggest with links to the same page viewed in those other languages? That way there is still only one way to switch languages and the user can tell which metadata languages are available.
